const $ = (id) => document.getElementById(id);
const catalog = {
  conveyor: { name: 'Belt Conveyor', group: 'TRANSPORT', icon: '▰', desc: 'Memindahkan benda', color: '#cf9468', size: [3.4, 1.25], actuator: true },
  sensor: { name: 'Photoelectric', group: 'SENSORS', icon: '◉', desc: 'Deteksi benda', color: '#63d3c5', size: [.55, .55], sensor: true },
  stopper: { name: 'Stopper', group: 'ACTUATORS', icon: '▥', desc: 'Menahan benda', color: '#eab576', size: [.55, 1.15], actuator: true },
  pusher: { name: 'Pusher', group: 'ACTUATORS', icon: '⇥', desc: 'Dorong benda', color: '#e7a780', size: [.75, .85], actuator: true },
  emitter: { name: 'Box Emitter', group: 'MATERIAL', icon: '▣', desc: 'Keluarkan box', color: '#a3a5e3', size: [.9, .9], actuator: true },
  box: { name: 'Cardboard Box', group: 'MATERIAL', icon: '⬡', desc: 'Benda kerja', color: '#d9a36e', size: [.75, .75] },
  lamp: { name: 'Stack Light', group: 'SIGNALS', icon: '◍', desc: 'Indikator status', color: '#f0c86c', size: [.5, .5], actuator: true },
  button: { name: 'Push Button', group: 'SIGNALS', icon: '◌', desc: 'Input manual', color: '#e88f91', size: [.6, .6], sensor: true }
};
const initial = () => ({ parts: [
  { id: 'cv-a', type: 'conveyor', x: -2.8, z: -.4, rotation: 0, name: 'Infeed Conveyor', value: true },
  { id: 'cv-b', type: 'conveyor', x: .9, z: -.4, rotation: 0, name: 'Sorting Conveyor', value: true },
  { id: 'emit-a', type: 'emitter', x: -4.1, z: -.4, rotation: 0, name: 'Box Feeder', value: true },
  { id: 'sensor-a', type: 'sensor', x: .1, z: -.4, rotation: 0, name: 'Detection Sensor', value: false },
  { id: 'push-a', type: 'pusher', x: 1.8, z: -1.4, rotation: 0, name: 'Sorting Pusher', value: false },
  { id: 'stop-a', type: 'stopper', x: 3.3, z: -.4, rotation: 0, name: 'End Stopper', value: false },
  { id: 'lamp-a', type: 'lamp', x: 3.8, z: -2.2, rotation: 0, name: 'Run Indicator', value: true }
], rules: [{ id: 'rule-a', source: 'sensor-a', inverted: false, target: 'push-a', value: true }], version: 1 });
const saved = (() => { try { return JSON.parse(localStorage.getItem('factory-scene') || 'null'); } catch { return null; } })();
let scene = validScene(saved?.scene) ? saved.scene : initial();
let projectId = saved?.id || null;
let mode = 'edit', paused = false, selected = null, placing = null, activeTab = 'io';
let camera = { x: 0, y: 25, zoom: 1 }, mouse = { x: 0, y: 0 }, dragging = null;
let sim = { time: 0, boxes: [], events: [], emitterClock: 0, sensorStates: {} };
let toastTimer, dirty = false, frameLast = 0, dpr = 1;
const canvas = $('stage'), ctx = canvas.getContext('2d');
const key = (() => { let v = localStorage.getItem('factory-workspace-key'); if (!v) { v = [...crypto.getRandomValues(new Uint8Array(32))].map(x => x.toString(16).padStart(2, '0')).join(''); localStorage.setItem('factory-workspace-key', v); } return v; })();
const safe = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid = () => crypto.randomUUID();
function validScene(s) { return s && Array.isArray(s.parts) && s.parts.length <= 250 && s.parts.every(p => p && catalog[p.type] && typeof p.x === 'number' && Number.isFinite(p.x) && Math.abs(p.x) < 100 && typeof p.z === 'number' && Number.isFinite(p.z) && Math.abs(p.z) < 100 && typeof p.id === 'string') && Array.isArray(s.rules) && s.rules.length <= 100; }
function notify(s) { $('toast').textContent = s; $('toast').classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => $('toast').classList.remove('show'), 2700); }
function markDirty() { dirty = true; $('save-status').textContent = 'Perubahan belum disimpan ke cloud'; localStorage.setItem('factory-scene', JSON.stringify({ id: projectId, title: $('scene-name').value, scene })); renderPalette(); renderInspector(); renderPanel(); }
function log(s) { sim.events.unshift({ time: sim.time.toFixed(1), message: s }); sim.events.length = Math.min(sim.events.length, 60); if (activeTab === 'events') renderPanel(); }
function setMode(next) { if (mode === next) return; mode = next; paused = false; placing = null; selected = null; if (next === 'run') { resetSim(); log('Simulation started'); } $('edit-btn').classList.toggle('active', next === 'edit'); $('run-btn').classList.toggle('active', next === 'run'); $('pause-btn').disabled = next !== 'run'; $('mode-indicator').classList.toggle('running', next === 'run'); $('mode-label').textContent = next === 'run' ? 'SIMULATION RUNNING' : 'EDITOR MODE'; $('engine-status').textContent = next === 'run' ? 'RUNNING' : 'READY'; renderPalette(); renderInspector(); renderPanel(); }
function resetSim() { sim = { time: 0, boxes: scene.parts.filter(p => p.type === 'box').map(p => ({ id: uid(), x: p.x, z: p.z, pushed: false })), events: [], emitterClock: 0, sensorStates: {} }; for (const p of scene.parts) { if (['sensor','pusher','stopper','button'].includes(p.type)) p.value = false; } renderPanel(); }
function project(x, z, h = 0) { const unit = 46 * camera.zoom; return { x: canvas.clientWidth / 2 + camera.x + (x - z) * unit, y: canvas.clientHeight / 2 + camera.y + (x + z) * unit * .48 - h * unit }; }
function unproject(sx, sy) { const unit = 46 * camera.zoom, a = (sx - canvas.clientWidth / 2 - camera.x) / unit, b = (sy - canvas.clientHeight / 2 - camera.y) / (unit * .48); return { x: (a + b) / 2, z: (b - a) / 2 }; }
function poly(points, fill, stroke, width = 1) { ctx.beginPath(); points.forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.closePath(); ctx.fillStyle = fill; ctx.fill(); if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = width; ctx.stroke(); } }
function diamond(x, z, w, depth, h, color, outline) { let a = project(x-w/2,z-depth/2,h), b = project(x+w/2,z-depth/2,h), c = project(x+w/2,z+depth/2,h), d = project(x-w/2,z+depth/2,h), C=project(x+w/2,z+depth/2,0), D=project(x-w/2,z+depth/2,0); poly([d,c,C,D],'#223846',outline); poly([b,c,C,project(x+w/2,z-depth/2,0)],'#314955',outline); poly([a,b,c,d],color,outline); }
function drawGrid() { ctx.fillStyle = document.body.classList.contains('light') ? '#dce8ec' : '#1a2d3b'; ctx.fillRect(0,0,canvas.clientWidth,canvas.clientHeight); const size = 18; for(let x=-size;x<=size;x++) { ctx.beginPath(); for(let z=-size;z<=size;z++) { const p=project(x,z); z===-size?ctx.moveTo(p.x,p.y):ctx.lineTo(p.x,p.y); } ctx.strokeStyle=x===0?'#66808c88':'#718a9330';ctx.lineWidth=x===0?1.3:1;ctx.stroke(); } for(let z=-size;z<=size;z++) { ctx.beginPath(); for(let x=-size;x<=size;x++) { const p=project(x,z); x===-size?ctx.moveTo(p.x,p.y):ctx.lineTo(p.x,p.y); } ctx.strokeStyle=z===0?'#66808c88':'#718a9330';ctx.lineWidth=z===0?1.3:1;ctx.stroke(); } }
function drawPart(p, ghost = false) { const t=catalog[p.type], q=project(p.x,p.z); ctx.save(); ctx.globalAlpha=ghost?.6:1; const selectedPart = selected===p.id && mode==='edit'; const outline=selectedPart?'#ffd293':'#162632'; let w=t.size[0], dep=t.size[1]; if(p.rotation%2) [w,dep]=[dep,w]; if(p.type==='conveyor') { diamond(p.x,p.z,w,dep,.36,p.value?'#668390':'#4d5960',outline); for(let i=-1;i<=1;i++) { const start=p.rotation%2?project(p.x-.38,p.z+i*.8,.37):project(p.x+i*.8,p.z-.38,.37), end=p.rotation%2?project(p.x+.38,p.z+i*.8,.37):project(p.x+i*.8,p.z+.38,.37);ctx.beginPath();ctx.moveTo(start.x,start.y);ctx.lineTo(end.x,end.y);ctx.strokeStyle='#263c48';ctx.lineWidth=2;ctx.stroke(); } }
  else if(p.type==='box') diamond(p.x,p.z,.72,.72,.69,'#d9a570',outline);
  else if(p.type==='sensor') { diamond(p.x,p.z,.65,.65,.48,'#4ba79e',outline); ctx.beginPath();ctx.arc(q.x,q.y-30*camera.zoom,5*camera.zoom,0,7);ctx.fillStyle=p.value?'#9dffcb':'#9bebeb';ctx.fill(); if(mode==='run'){ctx.strokeStyle='#7ef6d072';ctx.setLineDash([4,4]);ctx.beginPath();let e=project(p.x,p.z+1.2,.4);ctx.moveTo(q.x,q.y-22*camera.zoom);ctx.lineTo(e.x,e.y);ctx.stroke();ctx.setLineDash([]);} }
  else if(p.type==='stopper') diamond(p.x,p.z,.42,1.1,p.value?.9:.35,'#f1ac66',outline);
  else if(p.type==='pusher') {diamond(p.x,p.z,.8,.8,.42,'#d49a80',outline); if(p.value) diamond(p.x+.5,p.z,.55,.42,.5,'#f5caa0',outline);}
  else if(p.type==='emitter') diamond(p.x,p.z,.95,.95,1.35,'#898dc6',outline);
  else if(p.type==='lamp') {diamond(p.x,p.z,.32,.32,1.45,'#6c8790',outline);ctx.beginPath();ctx.arc(q.x,q.y-69*camera.zoom,7*camera.zoom,0,7);ctx.fillStyle=p.value?'#ffe480':'#62747d';ctx.fill();}
  else if(p.type==='button') {diamond(p.x,p.z,.62,.62,.78,'#70828a',outline);ctx.beginPath();ctx.arc(q.x,q.y-36*camera.zoom,5*camera.zoom,0,7);ctx.fillStyle=p.value?'#ffbe9a':'#da736d';ctx.fill();}
  if(selectedPart){ctx.setLineDash([4,4]);ctx.strokeStyle='#ffbe80';ctx.strokeRect(q.x-32*camera.zoom,q.y-65*camera.zoom,64*camera.zoom,80*camera.zoom);ctx.setLineDash([]);} if(camera.zoom>.65){ctx.font=`${Math.max(9,10*camera.zoom)}px DM Sans`;ctx.fillStyle='#e9f2f4';ctx.textAlign='center';ctx.fillText(p.name||t.name,q.x,q.y+29*camera.zoom);}ctx.restore(); }
function drawBox(b){diamond(b.x,b.z,.69,.69,.68,'#deb17e','#6c513d');}
function draw(){ if(!canvas.clientWidth||!canvas.clientHeight)return;ctx.setTransform(dpr,0,0,dpr,0,0);drawGrid();const all=scene.parts.filter(p=>p.type!=='box').slice().sort((a,b)=>(a.x+a.z)-(b.x+b.z)); if(mode==='edit')all.push(...scene.parts.filter(p=>p.type==='box'));all.forEach(p=>drawPart(p));if(mode==='run')sim.boxes.slice().sort((a,b)=>(a.x+a.z)-(b.x+b.z)).forEach(drawBox);if(placing&&mode==='edit'){const p=unproject(mouse.x,mouse.y);drawPart({type:placing,x:Math.round(p.x*2)/2,z:Math.round(p.z*2)/2,rotation:0,name:catalog[placing].name},true);} }
function resize(){const rect=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));draw();} new ResizeObserver(resize).observe(canvas);
function step(dt){if(mode!=='run'||paused)return;dt=Math.min(dt,.07)*Number($('speed').value);sim.time+=dt;sim.emitterClock+=dt;const emitters=scene.parts.filter(p=>p.type==='emitter'&&p.value);if(sim.emitterClock>2.8&&sim.boxes.length<40){for(const p of emitters){if(!sim.boxes.some(b=>Math.abs(b.x-p.x)<.8&&Math.abs(b.z-p.z)<.8)){sim.boxes.push({id:uid(),x:p.x,z:p.z,pushed:false});log(`${p.name}: box emitted`);}}sim.emitterClock=0;}
  for(const s of scene.parts.filter(p=>p.type==='sensor')){const hit=sim.boxes.some(b=>Math.abs(b.x-s.x)<.46&&Math.abs(b.z-s.z)<.6);if(Boolean(s.value)!==hit){s.value=hit;log(`${s.name}: ${hit?'ON':'OFF'}`);}}
  for(const rule of scene.rules){const src=scene.parts.find(p=>p.id===rule.source),dst=scene.parts.find(p=>p.id===rule.target);if(src&&dst&&!dst.forced){dst.value=(Boolean(src.value)!==Boolean(rule.inverted))?Boolean(rule.value):!Boolean(rule.value);}}
  for(const b of sim.boxes){const cv=scene.parts.find(p=>p.type==='conveyor'&&p.value&&Math.abs(b.z-p.z)<.57&&Math.abs(b.x-p.x)<1.95);const stopper=scene.parts.find(p=>p.type==='stopper'&&p.value&&Math.abs(b.z-p.z)<.65&&b.x<p.x&&p.x-b.x<.54);if(cv&&!stopper)b.x+=dt*.88;const push=scene.parts.find(p=>p.type==='pusher'&&p.value&&Math.abs(b.x-p.x)<.55&&Math.abs(b.z-p.z)<1.25);if(push&&b.z<push.z+1.45)b.z+=dt*1.55;}sim.boxes=sim.boxes.filter(b=>Math.abs(b.x)<13&&Math.abs(b.z)<13);$('sim-time').textContent=`SIM TIME ${String(Math.floor(sim.time/60)).padStart(2,'0')}:${(sim.time%60).toFixed(1).padStart(4,'0')}`;}
function frame(t){const dt=frameLast?(t-frameLast)/1000:0;frameLast=t;step(dt);draw();requestAnimationFrame(frame);}requestAnimationFrame(frame);
function renderPalette(){let groups={};for(const [type,p] of Object.entries(catalog))(groups[p.group]??=[]).push([type,p]);$('palette').innerHTML=Object.entries(groups).map(([group,parts])=>`<div class="palette-section"><div class="section-label">${group}</div>${parts.map(([type,p])=>`<button class="palette-item ${placing===type?'selected':''}" data-part="${type}" ${mode==='run'?'disabled':''}><span class="part-icon">${p.icon}</span><span><strong>${p.name}</strong><small>${p.desc}</small></span></button>`).join('')}</div>`).join('');$('part-count').textContent=String(Object.keys(catalog).length).padStart(2,'0');$('palette').querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{placing=placing===b.dataset.part?null:b.dataset.part;selected=null;renderPalette();renderInspector();$('stage-hint').textContent=placing?'Klik grid untuk menempatkan · Esc batal':'Pilih komponen di kiri untuk mulai membangun';});}
function renderInspector(){const host=$('inspector-content');const p=scene.parts.find(p=>p.id===selected);if(!p){host.innerHTML=`<div class="inspector-empty"><span class="empty-graphic">◇</span><h3>${mode==='run'?'Simulasi aktif':'Tidak ada objek dipilih'}</h3><p>${mode==='run'?'Pantau tag dan jalankan kontrol pada panel bawah.':'Klik komponen dalam scene untuk melihat dan mengubah propertinya.'}</p></div>`;return;}host.innerHTML=`<div class="inspector-content"><h2>${safe(p.name)}</h2><div class="type-name">${safe(catalog[p.type].name)}</div><div class="prop-group"><span class="prop-label">IDENTITY</span><div class="prop-field"><label>Nama tag / objek</label><input id="prop-name" maxlength="60" value="${safe(p.name)}" ${mode==='run'?'disabled':''}></div><div class="prop-field"><label>Tipe komponen</label><input value="${safe(catalog[p.type].name)}" disabled></div></div><div class="prop-group"><span class="prop-label">TRANSFORM</span><div class="row-fields"><div class="prop-field"><label>Posisi X</label><input id="prop-x" type="number" min="-30" max="30" step="0.5" value="${p.x}" ${mode==='run'?'disabled':''}></div><div class="prop-field"><label>Posisi Z</label><input id="prop-z" type="number" min="-30" max="30" step="0.5" value="${p.z}" ${mode==='run'?'disabled':''}></div></div><div class="prop-field"><label>Rotasi</label><select id="prop-rotation" ${mode==='run'?'disabled':''}>${[0,90,180,270].map((v,i)=>`<option value="${i}" ${p.rotation===i?'selected':''}>${v}°</option>`).join('')}</select></div></div>${catalog[p.type].actuator||catalog[p.type].sensor?`<div class="prop-group"><span class="prop-label">I/O STATE</span><div class="tag-card"><div><small>${catalog[p.type].sensor?'INPUT · DIGITAL':'OUTPUT · DIGITAL'}</small><strong>${safe(p.name)}</strong></div><span class="tag-value ${p.value?'on':''}">${p.value?'ON':'OFF'}</span></div></div>`:''}${mode==='edit'?`<div class="inspector-actions"><button id="duplicate-part">⧉ Duplikat</button><button id="remove-part" class="danger">⌫ Hapus</button></div>`:''}</div>`;
  if(mode==='edit'){for(const field of ['name','x','z','rotation']){const el=$(`prop-${field}`);el.onchange=()=>{let v=field==='name'?el.value.trim().slice(0,60):Number(el.value);if(field==='name'&&!v)v=catalog[p.type].name;if(field==='x'||field==='z')v=Math.min(30,Math.max(-30,Number.isFinite(v)?v:0));p[field]=v;markDirty();};} $('duplicate-part').onclick=()=>{const copy={...p,id:uid(),name:p.name+' copy',x:p.x+1,z:p.z+1};scene.parts.push(copy);selected=copy.id;markDirty();};$('remove-part').onclick=removeSelected;}}
function ioTags(){return scene.parts.filter(p=>catalog[p.type].sensor||catalog[p.type].actuator);}
function renderPanel(){const host=$('panel-content');if(activeTab==='io'){const tags=ioTags();host.innerHTML=tags.length?`<div class="monitor-grid">${tags.map(p=>`<div class="tag-card"><div><small>${catalog[p.type].sensor?'INPUT':'OUTPUT'} · ${p.type.toUpperCase()}</small><strong title="${safe(p.name)}">${safe(p.name)}</strong></div><button class="tag-value ${p.value?'on':''} ${catalog[p.type].actuator?'force':''}" data-toggle="${safe(p.id)}" title="${catalog[p.type].actuator?'Klik untuk force tag':'Input sensor'}">${p.value?'ON':'OFF'}</button></div>`).join('')}</div>`:'<div class="empty-panel">Tambahkan sensor atau aktuator untuk melihat tag I/O.</div>';host.querySelectorAll('[data-toggle]').forEach(btn=>btn.onclick=()=>{const p=scene.parts.find(x=>x.id===btn.dataset.toggle);if(!p||!catalog[p.type].actuator)return;p.value=!p.value;p.forced=true;log(`${p.name}: forced ${p.value?'ON':'OFF'}`);markDirty();});}
  else if(activeTab==='events')host.innerHTML=sim.events.length?sim.events.map(e=>`<div class="event-row"><time>${safe(e.time)}s</time><span>${safe(e.message)}</span></div>`).join(''):'<div class="empty-panel">Peristiwa simulasi akan muncul di sini. Tekan RUN untuk memulai.</div>';
  else {const sources=scene.parts.filter(p=>catalog[p.type].sensor),targets=scene.parts.filter(p=>catalog[p.type].actuator);host.innerHTML=`<div class="logic-list">${scene.rules.map(r=>`<div class="logic-row" data-rule="${safe(r.id)}"><span>WHEN</span><select data-field="source">${sources.map(p=>`<option value="${safe(p.id)}" ${r.source===p.id?'selected':''}>${safe(p.name)}</option>`).join('')}</select><select data-field="inverted"><option value="false" ${!r.inverted?'selected':''}>IS ON</option><option value="true" ${r.inverted?'selected':''}>IS OFF</option></select><span>THEN</span><select data-field="target">${targets.map(p=>`<option value="${safe(p.id)}" ${r.target===p.id?'selected':''}>${safe(p.name)}</option>`).join('')}</select><select data-field="value"><option value="true" ${r.value?'selected':''}>ON</option><option value="false" ${!r.value?'selected':''}>OFF</option></select><button class="delete-rule" title="Hapus aturan">✕</button></div>`).join('')}</div><button class="add-rule" ${!sources.length||!targets.length?'disabled':''}>+ Tambah aturan</button>${!sources.length||!targets.length?'<div class="empty-panel">Tambahkan input dan output untuk membuat aturan.</div>':''}`;host.querySelector('.add-rule').onclick=()=>{scene.rules.push({id:uid(),source:sources[0].id,inverted:false,target:targets[0].id,value:true});markDirty();};host.querySelectorAll('[data-rule]').forEach(row=>{const rule=scene.rules.find(x=>x.id===row.dataset.rule);row.querySelectorAll('select').forEach(el=>el.onchange=()=>{rule[el.dataset.field]=['value','inverted'].includes(el.dataset.field)?el.value==='true':el.value;markDirty();});row.querySelector('.delete-rule').onclick=()=>{scene.rules=scene.rules.filter(x=>x!==rule);markDirty();};});}}
function removeSelected(){if(!selected||mode==='run')return;scene.parts=scene.parts.filter(p=>p.id!==selected);scene.rules=scene.rules.filter(r=>r.source!==selected&&r.target!==selected);selected=null;markDirty();}
function pick(sx,sy){let candidates=scene.parts.map(p=>({p,q:project(p.x,p.z)})).filter(({p,q})=>{let wide=p.type==='conveyor'?88:34;return Math.abs(sx-q.x)<wide*camera.zoom&&Math.abs(sy-(q.y-15*camera.zoom))<42*camera.zoom;});return candidates.sort((a,b)=>Math.hypot(a.q.x-sx,a.q.y-sy)-Math.hypot(b.q.x-sx,b.q.y-sy))[0]?.p;}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);let r=canvas.getBoundingClientRect();mouse={x:e.clientX-r.left,y:e.clientY-r.top};if(mode==='edit'&&placing){const p=unproject(mouse.x,mouse.y);const type=placing;const part={id:uid(),type,x:Math.round(p.x*2)/2,z:Math.round(p.z*2)/2,rotation:0,name:catalog[type].name+' '+(scene.parts.filter(x=>x.type===type).length+1),value:type==='conveyor'||type==='emitter'};scene.parts.push(part);selected=part.id;placing=null;markDirty();$('stage-hint').textContent='Klik komponen untuk mengubah propertinya';return;}const picked=pick(mouse.x,mouse.y);if(mode==='edit'){selected=picked?.id||null;renderInspector();if(picked)dragging={kind:'part',id:picked.id,startX:mouse.x,startY:mouse.y,originalX:picked.x,originalZ:picked.z};else dragging={kind:'pan',x:mouse.x,y:mouse.y,cameraX:camera.x,cameraY:camera.y};}else {if(picked?.type==='button'){picked.value=!picked.value;log(`${picked.name}: ${picked.value?'pressed':'released'}`);renderPanel();}else dragging={kind:'pan',x:mouse.x,y:mouse.y,cameraX:camera.x,cameraY:camera.y};}});
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();mouse={x:e.clientX-r.left,y:e.clientY-r.top};const w=unproject(mouse.x,mouse.y);$('hover-coords').textContent=`X ${w.x.toFixed(1)} · Z ${w.z.toFixed(1)}`;if(!dragging)return;if(dragging.kind==='pan'){camera.x=dragging.cameraX+mouse.x-dragging.x;camera.y=dragging.cameraY+mouse.y-dragging.y;}else {const p=scene.parts.find(p=>p.id===dragging.id);if(p){const start=unproject(dragging.startX,dragging.startY);p.x=Math.round((dragging.originalX+w.x-start.x)*2)/2;p.z=Math.round((dragging.originalZ+w.z-start.z)*2)/2;renderInspector();}}});
canvas.addEventListener('pointerup',()=>{if(dragging?.kind==='part')markDirty();dragging=null;});canvas.addEventListener('pointercancel',()=>dragging=null);
canvas.addEventListener('wheel',e=>{e.preventDefault();camera.zoom=Math.min(2.4,Math.max(.45,camera.zoom*(e.deltaY>0?.9:1.1)));$('zoom-label').textContent=Math.round(camera.zoom*100)+'%';},{passive:false});
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.key==='F5'){e.preventDefault();setMode(mode==='edit'?'run':'edit');}if(e.key==='Escape'){placing=null;renderPalette();}if((e.key==='Delete'||e.key==='Backspace')&&selected)removeSelected();if(e.key.toLowerCase()==='r'&&selected&&mode==='edit'){const p=scene.parts.find(p=>p.id===selected);p.rotation=(p.rotation+1)%4;markDirty();}});
function template(){if(scene.parts.length&&!confirm('Ganti scene saat ini dengan template Sorting Line? Simpan atau ekspor dulu bila perlu.'))return;scene=initial();projectId=null;selected=null;setMode('edit');resetSim();$('scene-name').value='Conveyor Sorting Line';markDirty();notify('Template Sorting Line dimuat.');}
function download(){const data={format:'factory-web-lab',version:1,title:$('scene-name').value,scene};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=($('scene-name').value.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'factory-scene')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);notify('File proyek berhasil diekspor.');}
async function cloud(method='GET',payload){const r=await fetch('/api/projects'+(method==='DELETE'?`?id=${encodeURIComponent(payload)}`:''),{method,headers:{'Content-Type':'application/json','x-workspace-key':key},body:method==='PUT'?JSON.stringify(payload):undefined});if(!r.ok){const data=await r.json().catch(()=>({}));throw Error(data.error||`Server ${r.status}`);}return r.status===204?{}:r.json();}
async function save(){localStorage.setItem('factory-scene',JSON.stringify({id:projectId,title:$('scene-name').value,scene}));$('save-status').textContent='Tersimpan lokal · menyimpan ke Neon…';try{const result=await cloud('PUT',{id:projectId,title:$('scene-name').value,scene});projectId=result.id;dirty=false;localStorage.setItem('factory-scene',JSON.stringify({id:projectId,title:$('scene-name').value,scene}));$('save-status').textContent='Tersimpan lokal + Neon';notify('Scene tersimpan ke Neon.');}catch(e){$('save-status').textContent='Tersimpan lokal · Neon belum aktif';notify(e.message);}}
async function projects(){const modal=$('modal-backdrop'),host=$('modal-content');modal.classList.remove('hidden');host.innerHTML='<div class="modal-actions"><button id="new-scene">+ Scene baru</button><button id="export-modal">↧ Ekspor scene</button></div><p class="modal-note">Scene aktif tersimpan otomatis di browser ini. Gunakan Simpan scene untuk menyinkronkan ke Neon. Kunci workspace tersimpan di browser ini, jadi ekspor JSON sebagai cadangan saat pindah perangkat.</p><div id="cloud-list">Memuat proyek Neon…</div>';$('new-scene').onclick=()=>{if(!confirm('Buat scene kosong? Perubahan yang belum disimpan akan diganti.'))return;scene={parts:[],rules:[],version:1};projectId=null;selected=null;setMode('edit');$('scene-name').value='Scene Baru';markDirty();modal.classList.add('hidden');};$('export-modal').onclick=download;try{const {projects}=await cloud();$('cloud-list').innerHTML=projects.length?projects.map(p=>`<div class="project-row"><div><strong>${safe(p.title)}</strong><small>${new Date(p.updated_at).toLocaleString('id-ID')} · ${p.scene.parts.length} komponen</small></div><div><button data-open="${safe(p.id)}">Buka</button> <button class="danger" data-delete="${safe(p.id)}">Hapus</button></div></div>`).join(''):'<p class="modal-note">Belum ada proyek di Neon.</p>';host.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const p=projects.find(x=>x.id===b.dataset.open);if(!p||!validScene(p.scene))return notify('Format scene tidak valid.');scene=p.scene;projectId=p.id;selected=null;setMode('edit');resetSim();$('scene-name').value=p.title;markDirty();dirty=false;$('save-status').textContent='Dimuat dari Neon';modal.classList.add('hidden');});host.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Hapus proyek cloud ini secara permanen?'))return;try{await cloud('DELETE',b.dataset.delete);if(projectId===b.dataset.delete)projectId=null;notify('Proyek cloud dihapus.');projectsModalRefresh();}catch(e){notify(e.message);}});}catch(e){$('cloud-list').innerHTML=`<p class="cloud-message">${safe(e.message)}</p>`;}}
function projectsModalRefresh(){projects();}
$('scene-name').value=saved?.title||'Conveyor Sorting Line';$('scene-name').oninput=markDirty;$('edit-btn').onclick=()=>setMode('edit');$('run-btn').onclick=()=>setMode('run');$('pause-btn').onclick=()=>{paused=!paused;$('pause-btn').textContent=paused?'▷':'Ⅱ';$('mode-label').textContent=paused?'SIMULATION PAUSED':'SIMULATION RUNNING';log(paused?'Simulation paused':'Simulation resumed');};$('reset-btn').onclick=()=>{resetSim();log('Simulation reset');notify('Simulasi direset.');};$('template-btn').onclick=template;$('export-btn').onclick=download;$('save-btn').onclick=save;$('projects-btn').onclick=projects;$('close-modal').onclick=()=>$('modal-backdrop').classList.add('hidden');$('modal-backdrop').onclick=e=>{if(e.target===$('modal-backdrop'))e.currentTarget.classList.add('hidden');};$('fit-btn').onclick=()=>{camera={x:0,y:25,zoom:1};$('zoom-label').textContent='100%';};$('zoom-in').onclick=()=>{camera.zoom=Math.min(2.4,camera.zoom*1.2);$('zoom-label').textContent=Math.round(camera.zoom*100)+'%';};$('zoom-out').onclick=()=>{camera.zoom=Math.max(.45,camera.zoom/1.2);$('zoom-label').textContent=Math.round(camera.zoom*100)+'%';};$('theme-btn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('factory-theme',document.body.classList.contains('light')?'light':'dark');};if(localStorage.getItem('factory-theme')==='light')document.body.classList.add('light');$('import-input').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>200000)throw Error('File terlalu besar.');const data=JSON.parse(await f.text());if(!validScene(data.scene))throw Error('Format scene tidak valid.');scene=data.scene;projectId=null;selected=null;setMode('edit');resetSim();$('scene-name').value=String(data.title||'Scene impor').slice(0,100);markDirty();notify('Scene diimpor.');}catch(err){notify(err.message);}e.target.value='';};document.querySelectorAll('.panel-tabs button').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;document.querySelectorAll('.panel-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderPanel();});renderPalette();renderInspector();renderPanel();resize();
