import { FactoryView } from './view3d.js';
import { PlcLink } from './plc.js';
const $ = (id) => document.getElementById(id);
const catalog = {
  conveyor: { name: 'Belt Conveyor', group: 'TRANSPORT', icon: '▰', desc: 'Memindahkan benda', color: '#cf9468', size: [3.4, 1.25], actuator: true },
  sensor: { name: 'Photoelectric', group: 'SENSORS', icon: '◉', desc: 'Deteksi benda', color: '#63d3c5', size: [.55, .55], sensor: true },
  stopper: { name: 'Stopper', group: 'ACTUATORS', icon: '▥', desc: 'Menahan benda', color: '#eab576', size: [.55, 1.15], actuator: true },
  pusher: { name: 'Pusher', group: 'ACTUATORS', icon: '⇥', desc: 'Dorong benda', color: '#e7a780', size: [.75, .85], actuator: true },
  emitter: { name: 'Box Emitter', group: 'MATERIAL', icon: '▣', desc: 'Keluarkan box', color: '#a3a5e3', size: [.9, .9], actuator: true },
  box: { name: 'Cardboard Box', group: 'MATERIAL', icon: '⬡', desc: 'Benda kerja', color: '#d9a36e', size: [.75, .75] },
  lamp: { name: 'Stack Light', group: 'SIGNALS', icon: '◍', desc: 'Indikator status', color: '#f0c86c', size: [.5, .5], actuator: true },
  button: { name: 'Push Button', group: 'SIGNALS', icon: '◌', desc: 'Input manual', color: '#e88f91', size: [.6, .6], sensor: true }
};
const initial = () => ({ parts: [
  { id: 'workpiece-a', type: 'box', x: -3.3, z: -.4, rotation: 0, name: 'Workpiece A', value: false },
  { id: 'workpiece-b', type: 'box', x: -1.7, z: -.4, rotation: 0, name: 'Workpiece B', value: false },
  { id: 'cv-a', type: 'conveyor', x: -2.8, z: -.4, rotation: 0, name: 'Infeed Conveyor', value: true },
  { id: 'cv-b', type: 'conveyor', x: .9, z: -.4, rotation: 0, name: 'Sorting Conveyor', value: true },
  { id: 'emit-a', type: 'emitter', x: -4.1, z: -.4, rotation: 0, name: 'Box Feeder', value: true },
  { id: 'sensor-a', type: 'sensor', x: .1, z: -.4, rotation: 0, name: 'Detection Sensor', value: false },
  { id: 'push-a', type: 'pusher', x: .25, z: -1.4, rotation: 0, name: 'Sorting Pusher', value: false },
  { id: 'stop-a', type: 'stopper', x: 3.3, z: -.4, rotation: 0, name: 'End Stopper', value: false },
  { id: 'lamp-a', type: 'lamp', x: 3.8, z: -2.2, rotation: 0, name: 'Run Indicator', value: true }
], rules: [{ id: 'rule-a', source: 'sensor-a', inverted: false, target: 'push-a', value: true }], version: 1 });
const saved = (() => { try { return JSON.parse(localStorage.getItem('factory-scene') || 'null'); } catch { return null; } })();
let scene = validScene(saved?.scene) ? saved.scene : initial();
let projectId = saved?.id || null;
let mode = 'edit', paused = false, selected = null, placing = null, activeTab = 'io';
let camera = { x: 0, y: 25, zoom: 1 }, mouse = { x: 0, y: 0 }, dragging = null;
let sim = { time: 0, boxes: [], events: [], emitterClock: 0, sensorStates: {} };
let toastTimer, dirty = false, frameLast = 0, dpr = 1;
const canvas = $('stage');
const view = new FactoryView(canvas);
const plc = new PlcLink({scene:()=>scene,notify,changed:markDirty,isRunning:()=>mode==='run'&&!paused});
const key = (() => { let v = localStorage.getItem('factory-workspace-key'); if (!v) { v = [...crypto.getRandomValues(new Uint8Array(32))].map(x => x.toString(16).padStart(2, '0')).join(''); localStorage.setItem('factory-workspace-key', v); } return v; })();
const safe = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid = () => crypto.randomUUID();
function validScene(s) { return s && Array.isArray(s.parts) && s.parts.length <= 250 && s.parts.every(p => p && catalog[p.type] && typeof p.x === 'number' && Number.isFinite(p.x) && Math.abs(p.x) < 100 && typeof p.z === 'number' && Number.isFinite(p.z) && Math.abs(p.z) < 100 && typeof p.id === 'string') && Array.isArray(s.rules) && s.rules.length <= 100; }
function notify(s) { $('toast').textContent = s; $('toast').classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => $('toast').classList.remove('show'), 2700); }
function markDirty() { dirty = true; $('save-status').textContent = 'Perubahan belum disimpan ke cloud'; localStorage.setItem('factory-scene', JSON.stringify({ id: projectId, title: $('scene-name').value, scene })); renderPalette(); renderInspector(); renderPanel(); }
function log(s) { sim.events.unshift({ time: sim.time.toFixed(1), message: s }); sim.events.length = Math.min(sim.events.length, 60); if (activeTab === 'events') renderPanel(); }
function setMode(next) { if (mode === next) return; mode = next; paused = false; placing = null; selected = null; if (next === 'run') { resetSim(); log('Simulation started'); } $('edit-btn').classList.toggle('active', next === 'edit'); $('run-btn').classList.toggle('active', next === 'run'); $('pause-btn').disabled = next !== 'run'; $('mode-indicator').classList.toggle('running', next === 'run'); $('mode-label').textContent = next === 'run' ? 'SIMULATION RUNNING' : 'EDITOR MODE'; $('engine-status').textContent = next === 'run' ? 'RUNNING' : 'READY'; renderPalette(); renderInspector(); renderPanel(); }
function resetSim() { sim = { time: 0, boxes: scene.parts.filter(p => p.type === 'box').map(p => ({ id: uid(), x: p.x, z: p.z, pushed: false })), events: [], emitterClock: 0, sensorStates: {} }; for (const p of scene.parts) { if (['sensor','pusher','stopper','button'].includes(p.type)) p.value = false; } renderPanel(); }
function draw(){view.sync(scene.parts,sim.boxes,selected,mode==='run');}
function resize(){view.resize();}
function step(dt){if(mode!=='run'||paused)return;dt=Math.min(dt,.07)*Number($('speed').value);sim.time+=dt;sim.emitterClock+=dt;const emitters=scene.parts.filter(p=>p.type==='emitter'&&p.value);if(sim.emitterClock>2.8&&sim.boxes.length<40){for(const p of emitters){if(!sim.boxes.some(b=>Math.abs(b.x-p.x)<.8&&Math.abs(b.z-p.z)<.8)){sim.boxes.push({id:uid(),x:p.x,z:p.z,pushed:false});log(`${p.name}: box emitted`);}}sim.emitterClock=0;}
  for(const s of scene.parts.filter(p=>p.type==='sensor')){const hit=sim.boxes.some(b=>Math.abs(b.x-s.x)<.46&&Math.abs(b.z-s.z)<.6);if(Boolean(s.value)!==hit){s.value=hit;log(`${s.name}: ${hit?'ON':'OFF'}`);}}
  if(!plc.enabled)for(const rule of scene.rules){const src=scene.parts.find(p=>p.id===rule.source),dst=scene.parts.find(p=>p.id===rule.target);if(src&&dst&&!dst.forced){dst.value=(Boolean(src.value)!==Boolean(rule.inverted))?Boolean(rule.value):!Boolean(rule.value);}}
  for(const b of sim.boxes){
    const local=(p)=>{const r=(p.rotation||0)*Math.PI/2,dx=b.x-p.x,dz=b.z-p.z;return {u:dx*Math.cos(r)+dz*Math.sin(r),v:-dx*Math.sin(r)+dz*Math.cos(r),r};};
    const cv=scene.parts.find(p=>{if(p.type!=='conveyor'||!p.value)return false;const l=local(p);return Math.abs(l.v)<.57&&Math.abs(l.u)<1.95;});
    const stopped=scene.parts.some(p=>p.type==='stopper'&&p.value&&Math.hypot(b.x-p.x,b.z-p.z)<.58);
    if(cv&&!stopped){const r=(cv.rotation||0)*Math.PI/2;b.x+=dt*.88*Math.cos(r);b.z+=dt*.88*Math.sin(r);}
    const push=scene.parts.find(p=>{if(p.type!=='pusher'||!p.value)return false;const l=local(p);return Math.abs(l.u)<.55&&l.v>0&&l.v<1.7;});
    if(push){const r=(push.rotation||0)*Math.PI/2;b.x-=dt*1.55*Math.sin(r);b.z+=dt*1.55*Math.cos(r);}
  }sim.boxes=sim.boxes.filter(b=>Math.abs(b.x)<13&&Math.abs(b.z)<13);$('sim-time').textContent=`SIM TIME ${String(Math.floor(sim.time/60)).padStart(2,'0')}:${(sim.time%60).toFixed(1).padStart(4,'0')}`;}
function frame(t){const dt=frameLast?(t-frameLast)/1000:0;frameLast=t;step(dt);draw();requestAnimationFrame(frame);}requestAnimationFrame(frame);
function renderPalette(){let groups={};for(const [type,p] of Object.entries(catalog))(groups[p.group]??=[]).push([type,p]);$('palette').innerHTML=Object.entries(groups).map(([group,parts])=>`<div class="palette-section"><div class="section-label">${group}</div>${parts.map(([type,p])=>`<button class="palette-item ${placing===type?'selected':''}" data-part="${type}" ${mode==='run'?'disabled':''}><span class="part-icon">${p.icon}</span><span><strong>${p.name}</strong><small>${p.desc}</small></span></button>`).join('')}</div>`).join('');$('part-count').textContent=String(Object.keys(catalog).length).padStart(2,'0');$('palette').querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{placing=placing===b.dataset.part?null:b.dataset.part;selected=null;renderPalette();renderInspector();$('stage-hint').textContent=placing?'Klik grid untuk menempatkan · Esc batal':'Pilih komponen di kiri untuk mulai membangun';});}
function renderInspector(){const host=$('inspector-content');const p=scene.parts.find(p=>p.id===selected);if(!p){host.innerHTML=`<div class="inspector-empty"><span class="empty-graphic">◇</span><h3>${mode==='run'?'Simulasi aktif':'Tidak ada objek dipilih'}</h3><p>${mode==='run'?'Pantau tag dan jalankan kontrol pada panel bawah.':'Klik komponen dalam scene untuk melihat dan mengubah propertinya.'}</p></div>`;return;}host.innerHTML=`<div class="inspector-content"><h2>${safe(p.name)}</h2><div class="type-name">${safe(catalog[p.type].name)}</div><div class="prop-group"><span class="prop-label">IDENTITY</span><div class="prop-field"><label>Nama tag / objek</label><input id="prop-name" maxlength="60" value="${safe(p.name)}" ${mode==='run'?'disabled':''}></div><div class="prop-field"><label>Tipe komponen</label><input value="${safe(catalog[p.type].name)}" disabled></div></div><div class="prop-group"><span class="prop-label">TRANSFORM</span><div class="row-fields"><div class="prop-field"><label>Posisi X</label><input id="prop-x" type="number" min="-30" max="30" step="0.5" value="${p.x}" ${mode==='run'?'disabled':''}></div><div class="prop-field"><label>Posisi Z</label><input id="prop-z" type="number" min="-30" max="30" step="0.5" value="${p.z}" ${mode==='run'?'disabled':''}></div></div><div class="prop-field"><label>Rotasi</label><select id="prop-rotation" ${mode==='run'?'disabled':''}>${[0,90,180,270].map((v,i)=>`<option value="${i}" ${p.rotation===i?'selected':''}>${v}°</option>`).join('')}</select></div></div>${catalog[p.type].actuator||catalog[p.type].sensor?`<div class="prop-group"><span class="prop-label">I/O STATE</span><div class="tag-card"><div><small>${catalog[p.type].sensor?'INPUT · DIGITAL':'OUTPUT · DIGITAL'}</small><strong>${safe(p.name)}</strong></div><span class="tag-value ${p.value?'on':''}">${p.value?'ON':'OFF'}</span></div></div>`:''}${mode==='edit'?`<div class="inspector-actions"><button id="duplicate-part">⧉ Duplikat</button><button id="remove-part" class="danger">⌫ Hapus</button></div>`:''}</div>`;
  if(mode==='edit'){for(const field of ['name','x','z','rotation']){const el=$(`prop-${field}`);el.onchange=()=>{let v=field==='name'?el.value.trim().slice(0,60):Number(el.value);if(field==='name'&&!v)v=catalog[p.type].name;if(field==='x'||field==='z')v=Math.min(30,Math.max(-30,Number.isFinite(v)?v:0));p[field]=v;markDirty();};} $('duplicate-part').onclick=()=>{const copy={...p,id:uid(),name:p.name+' copy',x:p.x+1,z:p.z+1};scene.parts.push(copy);selected=copy.id;markDirty();};$('remove-part').onclick=removeSelected;}}
function ioTags(){return scene.parts.filter(p=>catalog[p.type].sensor||catalog[p.type].actuator);}
function renderPanel(){const host=$('panel-content');if(activeTab==='io'){const tags=ioTags();host.innerHTML=tags.length?`<button id="release-forces" class="release-forces">Lepas semua force</button><div class="monitor-grid">${tags.map(p=>`<div class="tag-card"><div><small>${catalog[p.type].sensor?'INPUT':'OUTPUT'} · ${p.type.toUpperCase()}</small><strong title="${safe(p.name)}">${safe(p.name)}</strong></div><button class="tag-value ${p.value?'on':''} ${catalog[p.type].actuator?'force':''}" data-toggle="${safe(p.id)}" title="${catalog[p.type].actuator?'Klik untuk force tag':'Input sensor'}">${p.value?'ON':'OFF'}</button></div>`).join('')}</div>`:'<div class="empty-panel">Tambahkan sensor atau aktuator untuk melihat tag I/O.</div>';const release=host.querySelector('#release-forces');if(release)release.onclick=()=>{for(const p of scene.parts)p.forced=false;notify('Semua force dilepas.');};host.querySelectorAll('[data-toggle]').forEach(btn=>btn.onclick=()=>{const p=scene.parts.find(x=>x.id===btn.dataset.toggle);if(!p||!catalog[p.type].actuator)return;if(plc.enabled)return notify('Mode PLC aktif: aktuator mengikuti coil dari PLC.');p.value=!p.value;p.forced=true;log(`${p.name}: forced ${p.value?'ON':'OFF'}`);markDirty();});}
  else if(activeTab==='events')host.innerHTML=sim.events.length?sim.events.map(e=>`<div class="event-row"><time>${safe(e.time)}s</time><span>${safe(e.message)}</span></div>`).join(''):'<div class="empty-panel">Peristiwa simulasi akan muncul di sini. Tekan RUN untuk memulai.</div>';
  else {const sources=scene.parts.filter(p=>catalog[p.type].sensor),targets=scene.parts.filter(p=>catalog[p.type].actuator);host.innerHTML=`<div class="logic-list">${scene.rules.map(r=>`<div class="logic-row" data-rule="${safe(r.id)}"><span>WHEN</span><select data-field="source">${sources.map(p=>`<option value="${safe(p.id)}" ${r.source===p.id?'selected':''}>${safe(p.name)}</option>`).join('')}</select><select data-field="inverted"><option value="false" ${!r.inverted?'selected':''}>IS ON</option><option value="true" ${r.inverted?'selected':''}>IS OFF</option></select><span>THEN</span><select data-field="target">${targets.map(p=>`<option value="${safe(p.id)}" ${r.target===p.id?'selected':''}>${safe(p.name)}</option>`).join('')}</select><select data-field="value"><option value="true" ${r.value?'selected':''}>ON</option><option value="false" ${!r.value?'selected':''}>OFF</option></select><button class="delete-rule" title="Hapus aturan">✕</button></div>`).join('')}</div><button class="add-rule" ${!sources.length||!targets.length?'disabled':''}>+ Tambah aturan</button>${!sources.length||!targets.length?'<div class="empty-panel">Tambahkan input dan output untuk membuat aturan.</div>':''}`;host.querySelector('.add-rule').onclick=()=>{scene.rules.push({id:uid(),source:sources[0].id,inverted:false,target:targets[0].id,value:true});markDirty();};host.querySelectorAll('[data-rule]').forEach(row=>{const rule=scene.rules.find(x=>x.id===row.dataset.rule);row.querySelectorAll('select').forEach(el=>el.onchange=()=>{rule[el.dataset.field]=['value','inverted'].includes(el.dataset.field)?el.value==='true':el.value;markDirty();});row.querySelector('.delete-rule').onclick=()=>{scene.rules=scene.rules.filter(x=>x!==rule);markDirty();};});}}
function removeSelected(){if(!selected||mode==='run')return;scene.parts=scene.parts.filter(p=>p.id!==selected);scene.rules=scene.rules.filter(r=>r.source!==selected&&r.target!==selected);selected=null;markDirty();}
function pick(x,y){const id=view.pick(x,y);return scene.parts.find(p=>p.id===id);}
canvas.addEventListener('pointerdown',e=>{
 const rect=canvas.getBoundingClientRect();mouse={x:e.clientX-rect.left,y:e.clientY-rect.top};
 if(e.button!==0)return;
 if(mode==='edit'&&placing){view.controls.enabled=false;const w=view.ground(mouse.x,mouse.y),type=placing;if(scene.parts.length>=250)return notify('Maksimal 250 komponen.');const part={id:uid(),type,x:Math.round(w.x*2)/2,z:Math.round(w.z*2)/2,rotation:0,name:catalog[type].name+' '+(scene.parts.filter(p=>p.type===type).length+1),value:['conveyor','emitter'].includes(type)};scene.parts.push(part);selected=part.id;placing=null;markDirty();return;}
 const p=pick(mouse.x,mouse.y);
 if(mode==='edit'){selected=p?.id||null;renderInspector();if(p){view.controls.enabled=false;const start=view.ground(mouse.x,mouse.y);dragging={id:p.id,start,originalX:p.x,originalZ:p.z};}}
 else if(p?.type==='button'){p.value=!p.value;renderPanel();}
},true);
canvas.addEventListener('pointermove',e=>{const rect=canvas.getBoundingClientRect();mouse={x:e.clientX-rect.left,y:e.clientY-rect.top};const w=view.ground(mouse.x,mouse.y);$('hover-coords').textContent=`X ${w.x.toFixed(1)} · Z ${w.z.toFixed(1)}`;if(dragging){const p=scene.parts.find(p=>p.id===dragging.id);if(p){p.x=Math.max(-30,Math.min(30,Math.round((dragging.originalX+w.x-dragging.start.x)*2)/2));p.z=Math.max(-30,Math.min(30,Math.round((dragging.originalZ+w.z-dragging.start.z)*2)/2));}}});
const endDrag=()=>{if(dragging)markDirty();dragging=null;view.controls.enabled=true;};window.addEventListener('pointerup',endDrag);canvas.addEventListener('pointercancel',endDrag);
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.key==='F5'){e.preventDefault();setMode(mode==='edit'?'run':'edit');}if(e.key==='Escape'){placing=null;renderPalette();}if((e.key==='Delete'||e.key==='Backspace')&&selected)removeSelected();if(e.key.toLowerCase()==='r'&&selected&&mode==='edit'){const p=scene.parts.find(p=>p.id===selected);p.rotation=(p.rotation+1)%4;markDirty();}});
function template(){if(scene.parts.length&&!confirm('Ganti scene saat ini dengan template Sorting Line? Simpan atau ekspor dulu bila perlu.'))return;scene=initial();projectId=null;selected=null;setMode('edit');resetSim();$('scene-name').value='Conveyor Sorting Line';markDirty();notify('Template Sorting Line dimuat.');}
function download(){const data={format:'factory-web-lab',version:1,title:$('scene-name').value,scene};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=($('scene-name').value.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'factory-scene')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);notify('File proyek berhasil diekspor.');}
async function cloud(method='GET',payload){const r=await fetch('/api/projects'+(method==='DELETE'?`?id=${encodeURIComponent(payload)}`:''),{method,headers:{'Content-Type':'application/json','x-workspace-key':key},body:method==='PUT'?JSON.stringify(payload):undefined});if(!r.ok){const data=await r.json().catch(()=>({}));throw Error(data.error||`Server ${r.status}`);}return r.status===204?{}:r.json();}
async function save(){localStorage.setItem('factory-scene',JSON.stringify({id:projectId,title:$('scene-name').value,scene}));$('save-status').textContent='Tersimpan lokal · menyimpan ke Neon…';try{const result=await cloud('PUT',{id:projectId,title:$('scene-name').value,scene});projectId=result.id;dirty=false;localStorage.setItem('factory-scene',JSON.stringify({id:projectId,title:$('scene-name').value,scene}));$('save-status').textContent='Tersimpan lokal + Neon';notify('Scene tersimpan ke Neon.');}catch(e){$('save-status').textContent='Tersimpan lokal · Neon belum aktif';notify(e.message);}}
async function projects(){document.querySelector('.modal-head h2').textContent='Proyek saya';const modal=$('modal-backdrop'),host=$('modal-content');modal.classList.remove('hidden');host.innerHTML='<div class="modal-actions"><button id="new-scene">+ Scene baru</button><button id="export-modal">↧ Ekspor scene</button></div><p class="modal-note">Scene aktif tersimpan otomatis di browser ini. Gunakan Simpan scene untuk menyinkronkan ke Neon. Kunci workspace tersimpan di browser ini, jadi ekspor JSON sebagai cadangan saat pindah perangkat.</p><div id="cloud-list">Memuat proyek Neon…</div>';$('new-scene').onclick=()=>{if(!confirm('Buat scene kosong? Perubahan yang belum disimpan akan diganti.'))return;scene={parts:[],rules:[],version:1};projectId=null;selected=null;setMode('edit');$('scene-name').value='Scene Baru';markDirty();modal.classList.add('hidden');};$('export-modal').onclick=download;try{const {projects}=await cloud();$('cloud-list').innerHTML=projects.length?projects.map(p=>`<div class="project-row"><div><strong>${safe(p.title)}</strong><small>${new Date(p.updated_at).toLocaleString('id-ID')} · ${p.scene.parts.length} komponen</small></div><div><button data-open="${safe(p.id)}">Buka</button> <button class="danger" data-delete="${safe(p.id)}">Hapus</button></div></div>`).join(''):'<p class="modal-note">Belum ada proyek di Neon.</p>';host.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const p=projects.find(x=>x.id===b.dataset.open);if(!p||!validScene(p.scene))return notify('Format scene tidak valid.');scene=p.scene;projectId=p.id;selected=null;setMode('edit');resetSim();$('scene-name').value=p.title;markDirty();dirty=false;$('save-status').textContent='Dimuat dari Neon';modal.classList.add('hidden');});host.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Hapus proyek cloud ini secara permanen?'))return;try{await cloud('DELETE',b.dataset.delete);if(projectId===b.dataset.delete)projectId=null;notify('Proyek cloud dihapus.');projectsModalRefresh();}catch(e){notify(e.message);}});}catch(e){$('cloud-list').innerHTML=`<p class="cloud-message">${safe(e.message)}</p>`;}}
function projectsModalRefresh(){projects();}
$('scene-name').value=saved?.title||'Conveyor Sorting Line';$('scene-name').oninput=markDirty;$('edit-btn').onclick=()=>setMode('edit');$('run-btn').onclick=()=>setMode('run');$('pause-btn').onclick=()=>{paused=!paused;$('pause-btn').textContent=paused?'▷':'Ⅱ';$('mode-label').textContent=paused?'SIMULATION PAUSED':'SIMULATION RUNNING';log(paused?'Simulation paused':'Simulation resumed');};$('reset-btn').onclick=()=>{resetSim();log('Simulation reset');notify('Simulasi direset.');};$('template-btn').onclick=template;$('export-btn').onclick=download;$('save-btn').onclick=save;$('projects-btn').onclick=projects;$('close-modal').onclick=()=>$('modal-backdrop').classList.add('hidden');$('modal-backdrop').onclick=e=>{if(e.target===$('modal-backdrop'))e.currentTarget.classList.add('hidden');};$('fit-btn').onclick=()=>view.reset();$('zoom-in').onclick=()=>view.zoom(.85);$('zoom-out').onclick=()=>view.zoom(1.15);$('theme-btn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('factory-theme',document.body.classList.contains('light')?'light':'dark');};if(localStorage.getItem('factory-theme')==='light')document.body.classList.add('light');$('import-input').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>200000)throw Error('File terlalu besar.');const data=JSON.parse(await f.text());if(!validScene(data.scene))throw Error('Format scene tidak valid.');scene=data.scene;projectId=null;selected=null;setMode('edit');resetSim();$('scene-name').value=String(data.title||'Scene impor').slice(0,100);markDirty();notify('Scene diimpor.');}catch(err){notify(err.message);}e.target.value='';};document.querySelectorAll('.panel-tabs button').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;document.querySelectorAll('.panel-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderPanel();});renderPalette();renderInspector();renderPanel();resize();

$('plc-btn').onclick=()=>plc.open();
$('wiring-btn').onclick=()=>plc.wiring();
setInterval(()=>{if(activeTab==='io'&&mode==='run')renderPanel();plc.status();},250);
