export class PlcLink {
  constructor({scene, notify, changed, isRunning}) {
    Object.assign(this,{scene,notify,changed,isRunning});this.socket=null;this.connected=false;this.enabled=false;this.lastFrame=0;this.lastReply=0;this.state='Terputus';
    setInterval(()=>this.exchange(),100);
  }
  mapping(){const scene=this.scene();const tags=scene.parts.filter(p=>['sensor','button','conveyor','pusher','stopper','emitter','lamp'].includes(p.type));const old=Array.isArray(scene.plcMapping)?scene.plcMapping:[];const result=[];for(const p of tags){const direction=['sensor','button'].includes(p.type)?'input':'output';const candidate=old.find(m=>m.id===p.id&&m.direction===direction);let address=candidate?.address;const used=a=>result.some(m=>m.direction===direction&&m.address===a);if(!Number.isInteger(address)||address<0||address>255||used(address)){address=0;while(used(address))address++;}result.push({id:p.id,direction,address});}scene.plcMapping=result;return result;}
  setAddress(id,address){
    if(this.connected)throw new Error('Putuskan gateway sebelum mengubah mapping.');
    const mappings=this.mapping(), target=mappings.find(m=>m.id===id);
    if(!target||!Number.isInteger(address)||address<0||address>255||mappings.some(m=>m.id!==id&&m.direction===target.direction&&m.address===address))throw new Error('Alamat harus 0–255 dan unik pada area yang sama.');
    target.address=address;
    this.scene().plcMapping=mappings;
    this.changed();
  }
  disconnect(){this.socket?.close();this.socket=null;this.connected=false;this.state='Terputus';this.safeOutputs();this.status();}
  safeOutputs(){if(this.enabled)for(const p of this.scene().parts)if(!['sensor','button','box'].includes(p.type))p.value=false;}
  connect(url,token){let u;try{u=new URL(url);}catch{return this.notify('URL gateway tidak valid.');}if(!['ws:','wss:'].includes(u.protocol))return this.notify('Gunakan alamat ws:// atau wss://.');if(location.protocol==='https:'&&u.protocol==='ws:')return this.notify('Buka workspace lokal http://127.0.0.1:8765 setelah gateway dijalankan, atau gunakan gateway WSS dengan sertifikat tepercaya.');if(token.length<16)return this.notify('Masukkan token yang ditampilkan gateway.');this.disconnect();this.enabled=true;this.safeOutputs();this.state='Menghubungkan…';this.status();const socket=new WebSocket(u);this.socket=socket;socket.onopen=()=>socket.send(JSON.stringify({type:'auth',token}));socket.onmessage=e=>{let msg;try{msg=JSON.parse(e.data);}catch{return;}if(msg.type==='ready'){this.connected=true;this.lastReply=performance.now();this.state='Terhubung · Modbus TCP server';this.notify('Gateway terhubung. PLC dapat membaca input dan menulis coil.');this.status();}if(msg.type==='state'&&this.connected){this.lastReply=performance.now();if(this.isRunning()){for(const m of this.mapping().filter(m=>m.direction==='output')){const p=this.scene().parts.find(p=>p.id===m.id);p.value=Boolean(msg.coils?.[m.address]);p.forced=false;}}else this.safeOutputs();}if(msg.type==='error')this.notify(msg.message||'Gateway menolak koneksi.');};socket.onerror=()=>{this.state='Gateway tidak dapat dijangkau';this.status();};socket.onclose=()=>{if(this.socket!==socket)return;this.connected=false;this.state='Terputus';this.safeOutputs();this.status();};}
  exchange(){if(!this.enabled)return;if(!this.connected||!this.socket||this.socket.readyState!==1){this.safeOutputs();return;}if(performance.now()-this.lastReply>1500){this.disconnect();this.notify('Gateway timeout. Aktuator simulasi dihentikan.');return;}const inputs=Array(256).fill(false);if(this.isRunning())for(const m of this.mapping().filter(m=>m.direction==='input'))inputs[m.address]=Boolean(this.scene().parts.find(p=>p.id===m.id)?.value);this.socket.send(JSON.stringify({type:'frame',running:this.isRunning(),inputs}));}
  status(){const s=document.getElementById('plc-state');if(s)s.textContent=this.state;const indicator=document.getElementById('plc-indicator');if(indicator){indicator.textContent=this.enabled?(this.connected?'PLC ONLINE':'PLC OFFLINE'):'LOCAL LOGIC';indicator.classList.toggle('connected',this.connected);}}
  open(){const backdrop=document.getElementById('modal-backdrop');backdrop.classList.remove('hidden');document.querySelector('.modal-head h2').textContent='PLC connection';const host=document.getElementById('modal-content');const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));host.innerHTML=`<p class="modal-note">Modbus TCP · PLC sebagai client, gateway sebagai server. Sensor virtual → discrete inputs (FC02). Perintah PLC → coils (FC05/15). Alamat di bawah dimulai dari 0.</p><div class="connection-banner" id="plc-state"></div><div class="prop-field"><label>Mode pengendali</label><select id="controller-mode"><option value="local">Logika lokal</option><option value="plc" ${this.enabled?'selected':''}>PLC melalui gateway</option></select></div><div class="prop-field"><label>Alamat gateway WebSocket</label><input id="gateway-url" value="${location.protocol==='https:'?'ws://127.0.0.1:8765':`ws://${location.host}`}" /></div><div class="prop-field"><label>Token gateway (hanya untuk sesi ini)</label><input id="gateway-token" type="password" autocomplete="off" placeholder="Token dari terminal gateway" /></div><div class="modal-actions"><button id="connect-gateway">Hubungkan</button><button id="disconnect-gateway">Putuskan</button><button id="csv-mapping">Ekspor I/O CSV</button></div><details class="gateway-guide"><summary>Menjalankan gateway lokal</summary><p>Di komputer yang dapat dijangkau PLC, unduh repository lalu jalankan:</p><pre>npm ci\nnpm run build\nnpm run gateway</pre><p>Buka <a href="http://127.0.0.1:8765" target="_blank" rel="noopener">workspace lokal</a>, isi token dari terminal, lalu Hubungkan. Impor JSON scene dari aplikasi online untuk memindahkan scene. Default port Modbus: <b>1502</b>, Unit ID: <b>1</b>. Untuk PLC fisik, set MODBUS_HOST ke IP LAN komputer gateway. HTTPS online memerlukan WSS tepercaya; workspace lokal menghindari masalah mixed content.</p><a href="https://github.com/hudbrother62-coder/factory-io" target="_blank" rel="noopener">Buka repository dan panduan</a></details><table class="mapping-table"><thead><tr><th>Tag</th><th>Area</th><th>Alamat 0-based</th></tr></thead><tbody>${this.mapping().map(m=>{const p=this.scene().parts.find(p=>p.id===m.id);return `<tr><td>${esc(p.name)}</td><td>${m.direction==='input'?'Discrete input · FC02':'Coil · FC05/15'}</td><td><input data-address="${esc(m.id)}" type="number" min="0" max="255" value="${m.address}" /></td></tr>`;}).join('')}</tbody></table><p class="modal-note">Aktuator simulasi berhenti jika gateway terputus. Mode ini tidak menulis ke output fisik PLC. Program PLC harus memetakan alamat Modbus di atas.</p>`;
    this.status();host.querySelector('#controller-mode').onchange=e=>{if(e.target.value==='local'){this.disconnect();this.enabled=false;}else{this.enabled=true;this.safeOutputs();}this.status();};host.querySelector('#connect-gateway').onclick=()=>this.connect(host.querySelector('#gateway-url').value,host.querySelector('#gateway-token').value);host.querySelector('#disconnect-gateway').onclick=()=>this.disconnect();host.querySelector('#csv-mapping').onclick=()=>this.exportCsv();host.querySelectorAll('[data-address]').forEach(el=>el.onchange=()=>{try{this.setAddress(el.dataset.address,el.value.trim()===''?NaN:Number(el.value));this.notify('Mapping I/O tersimpan.');}catch(error){this.notify(error.message);this.open();}});
  }
  exportCsv(){const cell=s=>'"'+String(s).replace(/"/g,'""')+'"';const rows=[['Tag','Area','Zero-based address','Modbus function','Direction']];for(const m of this.mapping())rows.push([this.scene().parts.find(p=>p.id===m.id).name,m.direction==='input'?'Discrete input':'Coil',m.address,m.direction==='input'?'FC02':'FC05/FC15',m.direction==='input'?'Simulation to PLC':'PLC to simulation']);downloadFile(rows.map(r=>r.map(cell).join(',')).join('\n'),'factory-io-mapping.csv','text/csv');}
  wiring(){const mappings=this.mapping(),parts=this.scene().parts;const inputs=mappings.filter(m=>m.direction==='input'),outputs=mappings.filter(m=>m.direction==='output');const h=Math.max(430,Math.max(inputs.length,outputs.length)*76+150);const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const rows=(arr,left)=>arr.map((m,i)=>{const y=135+i*76,p=parts.find(p=>p.id===m.id);return `<rect x="${left?22:712}" y="${y-24}" width="226" height="54" rx="7" fill="#eaf2f5" stroke="#9eb6c1"/><text x="${left?34:724}" y="${y-3}" fill="#253f50" font-size="12">${escape(p.name.slice(0,70))}</text><text x="${left?34:724}" y="${y+16}" fill="#5e7888" font-size="10">${left?'SENSOR → DI':'COIL → ACTUATOR'} ${m.address}</text><path d="M ${left?248:610} ${y} H ${left?350:712}" fill="none" stroke="${left?'#159c92':'#d58433'}" stroke-width="2"/><circle cx="${left?350:610}" cy="${y}" r="4" fill="${p.value?'#35bc8e':'#718c9c'}"/><text x="${left?266:628}" y="${y-8}" fill="#647e8e" font-size="10">${left?'FC02':'FC05/15'}</text>`;}).join('');const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 ${h}" role="img" aria-label="Diagram wiring logika PLC Modbus TCP"><rect width="960" height="${h}" fill="#f8fbfc"/><text x="25" y="35" font-size="21" font-family="sans-serif" fill="#183544">PLC I/O · Logical wiring</text><text x="25" y="60" font-size="11" font-family="sans-serif" fill="#617985">Modbus TCP · Unit 1 · zero-based addressing · connection schedule</text><rect x="350" y="90" width="260" height="${h-145}" rx="12" fill="#243e50"/><text x="480" y="118" text-anchor="middle" font-family="sans-serif" font-size="14" fill="#e9f5fa">PLC ⇄ LOCAL GATEWAY</text>${rows(inputs,true)}${rows(outputs,false)}<text x="25" y="${h-20}" fill="#697e89" font-family="sans-serif" font-size="11">Logical I/O mapping only. Physical terminal wiring depends on the CPU, I/O module and sensor specification.</text></svg>`;document.getElementById('modal-backdrop').classList.remove('hidden');document.querySelector('.modal-head h2').textContent='Wiring & I/O schedule';document.getElementById('modal-content').innerHTML=`<p class="modal-note">Diagram koneksi logika yang dibuat dari scene dan mapping aktif. Alamat Modbus bukan nomor terminal listrik.</p><div class="wiring-preview">${svg}</div><div class="modal-actions"><button id="download-wiring">Unduh SVG</button><button id="wiring-csv">Unduh daftar koneksi CSV</button></div><p class="modal-note">Wiring listrik 24 V, COM, PNP/NPN, dan relay belum ditentukan karena tipe PLC/modul belum diberikan. Diagram ini tidak digunakan sebagai petunjuk penyambungan daya.</p>`;document.getElementById('download-wiring').onclick=()=>downloadFile(svg,'factory-io-wiring.svg','image/svg+xml');document.getElementById('wiring-csv').onclick=()=>this.exportCsv();}
}
function downloadFile(content,name,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
